server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Any route that doesn't have a file extension will be redirected to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}