services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # Removed code volume to prevent Jenkins path errors.

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    # Removed code volume to prevent Jenkins path errors.
    environment:
      - MONGO_URI=${MONGO_URI}

  ai-engine:
    build: ./ai-engine
    ports:
      - "8000:8000"
    environment:
      - SARVAM_API_KEY=${SARVAM_API_KEY}